Changes in Readme
hasura/js-sdk pull request #6
Opened 2017-07-21 14:37 UTC by AbhishekBhattacharya

Changes made in accordance with the issue faced regarding **onSuccess** and **onError** that are functions that should be defined.Thus, should be added in the readme.

2017-07-21 19:57 UTC, coco98 commented
@AbhishekBhattacharya Thanks for the PR :) 
There are some mistakes in your README syntax. Some of the code is missing and ``` are showing up. I'm adding comments to your code commits to help you locate the mistakes.

You should always test/view your changes before you submit contributions.

2017-07-21 20:03 UTC, coco98 requested changes
I've added a lot of suggestions. Please note, that these are extremely simple changes that I could have just copy-pasted, but I hope this is a good learning experience for you!

2017-07-21 20:03 UTC, coco98 commented on README.md
> +```
This should be:
```
```javascript
```
That will enable javascript syntax highlighting.

2017-07-21 20:03 UTC, coco98 commented on README.md
> +
Put the 2 lines above, outside the beginning ``` javascript
In the final README, this is how it should appear:

**Option 1:**
Use lambdas or anonymous functions directly for handling success/error.

```javascript
hasura.data.query
...
```

2017-07-21 20:03 UTC, coco98 commented on README.md
> +
End the code fragment here by adding a  ```.

2017-07-21 20:03 UTC, coco98 commented on README.md
> +function mySuccessHandler (data) {
Begin a new code fragment above this line. Again, use ```javascript to start the code block.
Read more about code blocks here: https://help.github.com/articles/creating-and-highlighting-code-blocks/

2017-07-22 05:53 UTC, AbhishekBhattacharya commented
Thanks, @coco98  for your help! It was a great experience :100: 
I have done your requested changes.Please review them and merge :+1:

2017-07-22 15:00 UTC, coco98 commented on README.md
>  **NOTE**: In the examples below, `onSuccess` and `onError` are callback functions that you must implement.
This line is redundant now right? You should remove it.

2017-07-22 15:01 UTC, coco98 commented on README.md
> +The Data Query can be implemented as:
This portion is also redundant now. "The data query can be implemented as" and the entire code block below it too.

2017-07-22 15:02 UTC, coco98 commented
@AbhishekBhattacharya Added 2 more comments. Fix those and we should be good to merge!

2017-07-22 15:02 UTC, coco98 approved these changes

2017-07-22 15:33 UTC, AbhishekBhattacharya reviewed
Changed the Readme about handling onSuccess and onError callback functions

2017-07-22 15:34 UTC, AbhishekBhattacharya commented
@coco98  Done! and thanks a lot for  your guidance :)

2017-07-22 15:51 UTC, merged